---
- name: add repo key
  apt_key: url=https://download.newrelic.com/548C16BF.gpg state=present

- name: add Newrelic repo
  apt_repository: repo='deb http://apt.newrelic.com/debian/ newrelic non-free' state=present

- name: install newrelic-php5
  apt: name=newrelic-php5 state=present

- name: run newrelic-install
  shell: newrelic-install install

- name: put /etc/php5/fpm/conf.d/newrelic.ini
  template: src=fpm-newrelic.ini dest=/etc/php5/fpm/conf.d/newrelic.ini
  notify: restart php-fpm

- name: put /etc/php5/mods-available/newrelic.ini
  template: src=mods-newrelic.ini dest=/etc/php5/mods-available/newrelic.ini
  notify: restart php-fpm
